[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pylint.main]
# Specify Python version you want to use
py-version = "3.9"

# Add any project-specific Python paths
init-hook='import sys; sys.path.append(".")'

# Configure the output format
output-format = "colorized"

[tool.pylint.messages_control]
# Disable specific warnings
disable = [
    "C0111",  # missing-docstring
    "R0913",  # too-many-arguments
    "W0212",  # protected-access
    "W0613",  # unused-argument
]

[tool.pylint.format]
# Maximum number of characters on a single line
max-line-length = 88

[tool.pylint.design]
# Maximum number of arguments for function / method
max-args = 8

# Maximum number of locals for function / method body
max-locals = 15

# Maximum number of return / yield for function / method body
max-returns = 6

[tool.mypy]
# Specify the Python version
python_version = "3.9"

# Disallow dynamic typing
disallow_any_unimported = true
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false

# Ensure type coverage
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true

# Warn about unused configurations
warn_unused_configs = true

# Strict optional checking
strict_optional = true

# Ignore missing imports for specific libraries
[[tool.mypy.overrides]]
module = [
    "pandas.*",
    "numpy.*",
    "pytest.*"
]
ignore_missing_imports = true

[tool.flake8]
# Maximum line length
max-line-length = 88

# Ignore specific errors
ignore = [
    "E203",  # whitespace before ':' (black compatibility)
    "W503",  # line break before binary operator
]

# Maximum complexity
max-complexity = 10

# Exclude files/directories
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.pytest.ini_options]
# Default pytest configuration
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

# Optional: Python version specifics
[tool.coverage.run]
source = ["src"]
omit = [
    "tests/*",
    "*/__init__.py"
]
