###############
# INPUT FILES
###############
## NUMBERS PARAMETERS
numbers_file_path: "/Users/gretagalliani/Library/Mobile Documents/com~apple~Numbers/Documents/Contabilità/Libro spese.numbers"

numbers_sheet_mappings:
  uscite: "expenses"
  entrate: "income"
  risparmi: "savings"

numbers_date_column: "Data"

# Raw data paths
raw_paths:
  expenses: "input/finance_raw_expenses.csv"
  income: "input/finance_raw_income.csv"
  savings: "input/finance_raw_savings.csv"

date_column_candidates:
  - "Data"

# Processed data paths
processed_expenses_path: "input/finance_processed_expenses.csv"
processed_income_path: "input/finance_processed_income.csv"
processed_savings_path: "input/finance_processed_savings.csv"
monthly_savings_path: "input/finance_monthly_savings.csv"

###############
# OUTPUT DATASETS
###############
output_folder: "output"

# Monthly summary datasets
monthly_expenses_path: "output/monthly_expenses.csv"
monthly_income_path: "output/monthly_income.csv"
monthly_summary_path: "output/monthly_summary.csv"

# Expenses breakdown
expenses_by_category_path: "output/expenses_by_category.csv"
expenses_stacked_path: "output/expenses_stacked.csv"

# Income breakdown
income_by_category_path: "output/income_by_category.csv"
income_stacked_path: "output/income_stacked.csv"

# Savings datasets
savings_metrics_path: "output/savings_metrics.csv"
savings_by_category_path: "output/savings_by_category.csv"
savings_allocation_path: "output/savings_allocation.csv"

###############
# COLUMN MAPPINGS
###############

# Expense sheet column mapping
expenses_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category"
  "Importo": "Value"

# Income sheet column mapping
income_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category"
  "Importo": "Value"

# Savings sheet column mapping (new format)
savings_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category"
  "Tipo categoria": "CategoryType"
  "Importo": "Value"

###############
# SHEET NAMES
###############
sheet_mappings:
  "uscite": "expenses"
  "entrate": "income"
  "risparmi": "savings"

###############
# SAVINGS TYPES
###############
savings_types:
  "Trasferimento": "Transfer"
  "Accantonamento": "Allocation"
  "Pagamento": "Payment"
  "Prelievo": "Withdrawal"

###############
# CATEGORIES
###############
# Valid categories for expenses
valid_expenses_categories:
  - "Altro"
  - "Benessere Personale"
  - "Cibo"
  - "Formazione"
  - "Imposte"
  - "Oggetti personali"
  - "Servizi"
  - "Spese mediche"
  - "Svago"
  - "Veicoli"
  - "Viaggi"

# Valid categories for income
valid_income_categories:
  - "Altro"
  - "Bonus"
  - "Extra"
  - "Finanza"
  - "Rimborso tasse"
  - "Stipendio"
  - "Welfare"

# Valid categories for savings
valid_savings_categories:
  - "Accantomenti generali"
  - "Risparmi generali"
  - "Fondo vacanze"
  - "Psicologa"

# Default category to use for unmapped or null categories
default_category: "Varie"  # Miscellaneous

###############
# COLOR PALETTE
###############
color_palette:
  income: "#078080"        # Mint/Teal
  expense: "#F45D48"       # Coral/Red
  balance: "#4361EE"       # Bright blue for balance
  background: "#FFFFFF"    # Pure white background
  headline: "#232323"      # Dark gray for headlines
  text: "#232323"          # Dark gray for body text

  # Savings section colors
  savings:
    general: "#078080"     # Mint/Teal
    vacation: "#F45D48"    # Coral/Red
    therapy: "#4FB9B9"     # Light teal
    misc: "#F6836B"        # Light coral
    total: "#6C3BCE"       # Vibrant purple
    allocation: "#078080"  # Mint/Teal
    spent: "#F45D48"       # Coral/Red

  # Category visualization colors - Vibrant with good contrast
  categories:
    - "#078080"    # Mint/Teal
    - "#F45D48"    # Coral/Red
    - "#6C3BCE"    # Vibrant purple
    - "#4FB9B9"    # Light teal
    - "#F6836B"    # Light coral
    - "#90EE90"    # Light green
    - "#FF9E80"    # Light orange
    - "#396159"    # Dark teal
    - "#CE4438"    # Dark coral
    - "#4A1E9E"    # Dark purple
    - "#FFD166"    # Vibrant yellow
    - "#FF70A6"    # Pink
    - "#26547C"    # Navy blue
    - "#EF476F"    # Bright pink
    - "#06D6A0"    # Bright teal
    - "#FFD23F"    # Gold
    - "#3A86FF"    # Bright blue
    - "#FB5607"    # Bright orange
    - "#9D4EDD"    # Lavender
    - "#00BBF9"    # Sky blue

###############
# CATEGORY COLOR MAPPINGS
###############
# Fixed color mappings for expense categories to ensure consistency
expense_category_colors:
  "Altro": "#F6836B"          # Light coral
  "Benessere Personale": "#FF70A6"  # Pink
  "Cibo": "#F45D48"           # Coral/Red
  "Formazione": "#6C3BCE"     # Vibrant purple
  "Imposte": "#396159"        # Dark teal
  "Oggetti personali": "#FF9E80"  # Light orange
  "Servizi": "#078080"        # Mint/Teal
  "Spese mediche": "#4FB9B9"  # Light teal
  "Svago": "#FFD166"          # Vibrant yellow
  "Veicoli": "#FB5607"        # Bright orange
  "Viaggi": "#3A86FF"         # Bright blue

# Fixed color mappings for income categories
income_category_colors:
  "Altro": "#4A1E9E"          # Dark purple
  "Bonus": "#FFD23F"          # Gold
  "Extra": "#90EE90"          # Light green
  "Finanza": "#26547C"        # Navy blue
  "Rimborso tasse": "#EF476F" # Bright pink
  "Stipendio": "#078080"      # Mint/Teal
  "Welfare": "#06D6A0"        # Bright teal

# Fixed color mappings for savings categories
savings_category_colors:
  "Accantomenti generali": "#9D4EDD"  # Lavender
  "Risparmi generali": "#06D6A0"      # Bright teal
  "Fondo vacanze": "#FFD166"          # Vibrant yellow
  "Psicologa": "#4FB9B9"              # Light teal

###############
# FONTS
###############
fonts:
  title_font: "Montserrat"
  body_font: "Open Sans"
  font_url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Open+Sans:wght@400;600&display=swap"

###############
# DASHBOARD SETTINGS
###############
date_display_format: "DD/MM/YYYY"

# Chart styling parameters
chart_styling:
  # Legend positioning
  legend_orientation: "h"
  legend_yanchor: "bottom"
  legend_y: -0.2
  legend_xanchor: "center"
  legend_x: 0.5

  # Margins
  margin_left: 50
  margin_right: 50
  margin_top: 60
  margin_bottom: 80

  # Hover styling
  hover_bgcolor: "white"
  hover_font_size: 14
  hover_font_family: "Open Sans"
