###############
# INPUT FILES 
###############
numbers_file_path: "/Users/gretagalliani/Library/Mobile Documents/com~apple~Numbers/Documents/Contabilità/Libro spese.numbers"

# Raw data paths
raw_expenses_path: "input/finance_raw_expenses.csv"
raw_income_path: "input/finance_raw_income.csv"
raw_savings_path: "input/finance_raw_savings.csv"

# Processed data paths
processed_expenses_path: "input/finance_processed_expenses.csv"
processed_income_path: "input/finance_processed_income.csv"
processed_savings_path: "input/finance_processed_savings.csv"
monthly_savings_path: "input/finance_monthly_savings.csv"

###############
# OUTPUT DATASETS
###############
output_folder: "output"

# Monthly summary datasets
monthly_expenses_path: "output/monthly_expenses.csv"
monthly_income_path: "output/monthly_income.csv"
monthly_summary_path: "output/monthly_summary.csv"

# Expenses breakdown
expenses_by_category_path: "output/expenses_by_category.csv"
expenses_stacked_path: "output/expenses_stacked.csv"

# Income breakdown
income_by_category_path: "output/income_by_category.csv"
income_stacked_path: "output/income_stacked.csv"

# Savings datasets
savings_metrics_path: "output/savings_metrics.csv"
savings_by_category_path: "output/savings_by_category.csv"
savings_allocation_path: "output/savings_allocation.csv"

###############
# COLUMN MAPPINGS
###############

# Expense sheet column mapping
expenses_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category"
  "Importo": "Value"

# Income sheet column mapping
income_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category"
  "Importo": "Value"

# Savings sheet column mapping (new format)
savings_column_mapping:
  "Data": "Date"
  "Descrizione": "Description"
  "Categoria": "Category" 
  "Tipo categoria": "CategoryType"
  "Importo": "Value"

###############
# SHEET NAMES
###############
sheet_mappings:
  "uscite": "expenses"
  "entrate": "income"
  "risparmi": "savings"

###############
# SAVINGS TYPES
###############
savings_types:
  "Trasferimento": "Transfer"
  "Accantonamento": "Allocation"
  "Pagamento": "Payment"
  "Prelievo": "Withdrawal"

###############
# CATEGORIES
###############
# Valid categories for expenses
valid_expense_categories:
  - "Altro"
  - "Benessere Personale"
  - "Cibo"
  - "Formazione"
  - "Imposte"
  - "Oggetti personali"
  - "Servizi"
  - "Spese mediche"
  - "Svago"
  - "Veicoli"
  - "Viaggi"

# Valid categories for income
valid_income_categories:
  - "Altro"
  - "Bonus"
  - "Extra"
  - "Finanza"
  - "Rimborso tasse"
  - "Stipendio"
  - "Welfare" 

# Valid categories for savings
valid_savings_categories:
  - "Accantomenti generali"
  - "Risparmi generali"
  - "Fondo vacanze"
  - "Psicologa"

# Default category to use for unmapped or null categories
default_category: "Varie"  # Miscellaneous

###############
# COLOR PALETTE
###############
color_palette:
  # Main indicator colors - based on the inspirational schema
  income: "#078080"  # Teal from the Button color
  expense: "#f45d48"  # Coral/red from the Secondary color
  balance: "#232323"  # Dark gray from the Headline color
  background: "#f8f5f2"  # Warm cream from the Background color
  
  # Savings section colors - extending the palette with complementary colors
  savings:
    general: "#078080"      # Teal (main highlight color)
    vacation: "#f45d48"     # Coral (secondary color)
    therapy: "#619b8a"      # Muted teal/green (derived from highlight)
    misc: "#f7a399"         # Muted coral/pink (derived from secondary)
    total: "#232323"        # Dark gray (from headline)
    allocation: "#078080"   # Teal (highlight color)
    spent: "#f45d48"        # Coral (secondary color)
  
  # Category visualization colors - extended while maintaining the palette feeling
  categories:
    - "#078080"  # Teal (highlight)
    - "#f45d48"  # Coral (secondary)
    - "#232323"  # Dark gray (headline)
    - "#619b8a"  # Muted teal
    - "#f7a399"  # Muted coral
    - "#4fb9b9"  # Light teal
    - "#f6836b"  # Light coral
    - "#396159"  # Dark teal
    - "#ce4438"  # Dark coral
    - "#95b8b8"  # Very light teal
    - "#ffc4bc"  # Very light coral
    - "#505050"  # Medium gray
    - "#7da79a"  # Sage green (complementary)
    - "#e58e7d"  # Salmon (complementary)
    - "#1f4d4d"  # Very dark teal
    - "#d4cdc8"  # Light warm gray
    - "#86b3b3"  # Muted light teal
    - "#f8b1a8"  # Muted light coral
    - "#797168"  # Warm taupe
    - "#bde3e3"  # Pale teal


###############
# FONTS
###############
fonts:
  title_font: "Montserrat"
  body_font: "Open Sans"
  font_url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Open+Sans:wght@400;600&display=swap"